import Head from 'next/head'
import Counter from '../src/Components'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test Cypress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <div>J0der</div> */}
        <Counter/>
      </main>

    </div>
  )
}
